bleenco/bterm

.gitignore
.vscode/settings.json
src/electron.ts
yarn.lock

Only electron.ts should be merged.

BUG FIX: globalShortcut wasn't unregistered on appClose

---

config.json
package.json
src/app/menu.ts
src/electron.ts
src/utils.ts

Added feature for user notification, when new version of the application is available.

Auto update

---

config.json
src/app/app.component.ts
src/app/services/config.service.ts
src/electron.ts

This PR will close https://github.com/bleenco/bterm/issues/13

fix(): Application cannot be started in dist mode

---

e2e/app.e2e.ts

This PR is related to https://github.com/bleenco/bterm/issues/19

test(e2e): tests for minimize and right menu after click

---

e2e/app.e2e.ts

This PR relates to https://github.com/bleenco/bterm/issues/19

test(e2e): test on right menu and theme change

---

src/app/components/window-terminal/window-terminal.component.ts
src/app/services/hterm.service.ts
src/electron.ts
src/keyboard-shortcuts.ts

This PR will close https://github.com/bleenco/bterm/issues/27

fix():shortcut ctrl or cmd + K to clear the window

---

e2e/app.e2e.ts
src/app/components/window-top/window-top.component.html
src/app/components/window-top/window-top.component.ts
src/electron.ts

This PR will close https://github.com/bleenco/bterm/issues/25

fix(): double click on header tab does not maximize

---

e2e/app.e2e.ts
src/electron.ts

This PR will close https://github.com/bleenco/bterm/issues/29

fix(): Unable to close last window of the application

---

e2e/app.e2e.ts
src/app/components/window-sidebar/window-sidebar.component.html
src/app/components/window-sidebar/window-sidebar.component.ts
src/app/services/config.service.ts

This PR will close https://github.com/bleenco/bterm/issues/33

fix(): Theme selected is not shown

---

e2e/app.e2e.ts

This PR is related to https://github.com/bleenco/bterm/issues/19

test(e2e): more tests

---

e2e/app.e2e.ts

This PR will close https://github.com/bleenco/bterm/issues/19

test(e2e): switch tabs with numbers

---

src/app/components/window-top/window-top.component.html
src/styles/window-top.sass

This PR will close https://github.com/bleenco/bterm/issues/41

feat(): tab icons hover change

---

src/electron.ts
src/utils.ts

This PR will close https://github.com/bleenco/bterm/issues/34

fix(): new window opens it in cascade

---

src/app/components/window-terminal/window-terminal.component.ts
src/keyboard-shortcuts.ts

https://github.com/bleenco/bterm/issues/54

fix(): paste and copy fix (closes 54)

---

src/app/services/config.service.ts
src/styles/window-top.sass
src/utils.ts

this PR resolves a bug that caused the config file to be read and written continously

fix(): terminal config file loop bug

---

src/app/components/window-terminal/window-terminal.component.ts
src/electron.ts

fix(Linux): disable copy & paste on Linux and implement auto-copy functionallity

---

src/electron.ts

style(): window is shown after finished loading (closes 62)

---

src/app/components/window-top/window-top.component.html
src/app/components/window-top/window-top.component.ts
src/electron.ts
src/styles/window-top.sass

A click on title should now change the tab, but I'm looking into implementing a custom drag solution
This PR will get updated.

fix(): window dragging and tab selection (closes #53)

---

e2e/app.e2e.ts
src/app/components/window-top/window-top.component.html
src/app/services/config.service.ts
src/styles/window-top.sass

New close tab icon with style-able fill.

style(): new close icon with theming

---

src/app/services/config.service.ts
src/app/services/xterm.service.ts

Config service now has no dependencies from other services, which makes it universally injectable throughout the application.

refactor(): config service without dependencies

---

e2e/app.e2e.ts
src/app/components/window-top/window-top.component.html

Click event was not fired on middle click. Binding to the mousedown event solved the issue.

fix(): tab closing on middle click

---

.npmrc
package.json
src/app/app.module.ts
src/app/services/config.service.ts
src/app/services/pty.service.ts
yarn.lock

feat(): custom shell config option

---

e2e/app.e2e.ts
src/app/components/window-top/window-top.component.html
src/app/components/window-top/window-top.component.ts
src/styles/window-top.sass

This PR will close https://github.com/bleenco/bterm/issues/69

fix(): Minimizing icon in full screen

---

package.json

New release 0.9.3 codename "sensible cobra" with GIT Integration and several bug fixes.

chore(): release 0.9.3 "sensible cobra"

---

config.json
src/app/components/window-bottom/window-bottom.component.ts
src/app/services/git.service.ts

The GIT service was partially rewritten for better performance mostly on MacOS.
There is still some work to be done, like changing the fileExistsSync to async version.

fix(): Async GIT due to performance issues

---

src/app/components/window-bottom/window-bottom.component.ts
src/app/components/window-top/window-top.component.ts
src/app/services/pty.service.ts
src/app/services/xterm.service.ts
src/electron.ts
src/keyboard-shortcuts.ts

multiple major issues on Windows fixed.

Windows fixes

---

e2e/app.e2e.ts
src/app/components/window-terminal/window-terminal.component.ts

Fix: Make link unclickable. Closes #91

---

e2e/app.e2e.ts

There was an issue with the previos test, this should work now.

test(e2e): copy link on click fix

---

src/app/components/window-sidebar/window-sidebar.component.ts
src/app/services/config.service.ts
src/electron.ts

This PR forces the electron process to exit after 5 seconds of the last window being closed.

fix(): electron process sometimes doesn't exit

---

.gitignore
README.md

I updated README.md file with some basic  documentation for bterm cross-platform terminal

Updated README.md

---

src/app/services/config.service.ts

fix(): fonts on macOS issues

---

src/app/components/window-top/window-top.component.ts

window moving and empty title fix

fix(): title and window move fix

---

e2e/app.e2e.ts
package.json
tslint.json

abstruse gtihub webhook test. do not merge.

chore(testing): this commit serves for testing purposes

---

src/app/components/window-top/window-top.component.ts

Logical error in title updating fix.

fix(): tab title update fix

---

src/app/components/window-bottom/window-bottom.component.html
src/app/components/window-bottom/window-bottom.component.ts
src/styles/window-bottom.sass

Clicking on the current directory in bottom left corner opens the system file manager at that location.

feat(): open directory in system file manager

---

e2e/app.e2e.ts
src/app/components/window-sidebar/window-sidebar.component.html
src/app/components/window-sidebar/window-sidebar.component.ts

This this PR the user is able to select a custom shell which is not found with shelljs' "which" command.

Select a shell custom shell from system.

---

README.md
package-lock.json

docs(readme): update instructions

---

src/app/services/git.service.ts

This should prevent bterm freezes on start when no git is found.
Tested.

fix(): no git crash (closes #133)
